defaults:
  - _self_
  # - exp_settings

multi_head_attn_strategy: True
mode: "extracted_cot_vector" # "generate_self_cot", extracted_cot_vector
output_path: "/data1/wzy/cot-mimic/results/self_cot/causal"
ckpt_path: null
max_samples: 2000
model_name: qwen2.5-vl-7b-instruct
devices: 2
dtype: torch.float16
data:
  # name: "math_dataset"
  name: "mathvista"
  is_icl: False
  num_query_samples: 2000
  seed: 42
  num_shot: 0
  # subset: "testmini" # easy, hard, null
  num_workers: 5

resume: True
query_set: ${data.name}
query_set_size: null # the number of samples to evaluate. if set to null, all samples will be evaluated.
support_set: ${data.name}
# ckpt_path: "/data1/wzy/cot-mimic/results/average_cot_vectors/llama-3.1-8b-instruct_gsm8k_avg_cot_vector_mimic_withhs.pt"
batch_size: 4
iterations: null
max_skip_oom: 0
use_cot: False
generation_args:
  num_beams: 1
  max_new_tokens: 4096
  length_penalty: 0.0
  do_sample: False
  temperature: 0.0
  top_p: 1.0

# New: Evaluation mode
# "EVAL_BASELINE": 正常的baseline评估 (zero-shot/few-shot，无CoT向量)
# "EVAL_WITH_COT_VECTOR_ONESHOT": 评估训练好的CoT向量，学生模型输入 Q + 1-shot Ans 示例
# "EVAL_WITH_COT_VECTOR_DIRECT_Q": 评估训练好的CoT向量，学生模型输入 Q
# eval_mode: EVAL_WITH_COT_VECTOR_DIRECT_Q # 初始选择一种评估模式
eval_mode: EVAL_WITH_COT_VECTOR_DIRECT_Q # 初始选择一种评估模式

# 如果要评估训练好的CoT向量，需要指定ckpt_path
# ckpt_path: "null" # 替换为实际的检查点路径，例如 /home/ll26/data/cot-mimic/results/ckpt/YOUR_TRAIN_RUNNAME/epoch-X/encoder.pth

use_extracted_cot_vector: True # New parameter: set to True to use an extracted CoT vector
# use_extracted_cot_vector_type: "mimic"
use_extracted_cot_vector_type: "licv"
# extracted_cot_vector_path: "/data1/wzy/cot-mimic/results/average_cot_vectors/qwen2.5-math-7b-instruct_gsm8k_avg_cot_vector_mimic_withhs.pt"
extracted_cot_vector_path: "/data1/wzy/cot-mimic/results/average_cot_vectors/qwen2.5-vl-7b_gsm8k_avg_cot_vector_mimic.pt"
static_shift_scale: 0.3


# mode related arguments
# when mode == 'generate_self_cot', eval.py will generate self-cot for training

# If using extracted CoT vector, you can optionally set a static mu value
use_static_mu: True # Set to True to use a static mu value for extracted CoT vectors
static_mu_value: ${static_shift_scale}  # The static mu value to use when use_static_mu is True

use_base_vector: False  #licv version
# use_base_vector: True  #base version
# only_shift_at_layer: 0 # This parameter will be controlled by layer_eval_mode and run_eval_layers.py
only_shift_at_layer: 0 # This parameter will be controlled by layer_eval_mode and run_eval_layers.py

# Layer Evaluation Modes:
# 1. "single_layer": Iterate through layers from start_layer to end_layer.
# 2. "combinations": Iterate through pre-defined combinations in shift_layers_combinations.
# 3. "dense": all layers injected
layer_eval_mode: "single_layer" # Default mode

# Parameters for single_layer evaluation mode:
model_layers: 28 # Total number of layers in your model, e.g., 32 for llama
start_layer: 0   # Inclusive starting layer index for the loop
end_layer: 28    # Exclusive ending layer index for the loop (e.g., 32 means layers 0-31)
# end_layer: 28    # Exclusive ending layer index for the loop (e.g., 28 means layers 0-27)

# Parameters for combinations evaluation mode:
shift_layers_combinations: [[3,7]]

