defaults:
  - exp_settings
  - _self_

runname: "strategyqa-unimodal-internlm2_5-7b-chat-to-internvl-l17"
devices: 0
dtype: torch.bfloat16
resume: false
lr: ${peft.lr}
weight_decay: 1e-3
warmup_step: 0.1
batch_size: 1
epochs: 7
ce_loss_weight: ${peft.ce_loss_weight}
align_loss_weight: ${peft.align_loss_weight}
strategy: auto
accumulate_grad_batches: 4
grad_clip_val: 1.0
precision: bf16-mixed

method_name: trainable_unimodal_extracted_vector_recovery
benchmark_name: ${data.name}
recovery_vector_semantics: base

init_mode: unimodal_extracted
loss_mode: ce_align
random_init_std: 1e-3
align_num_tokens: 10

model_name: internvl2_5-8b
training-mode: TRAIN_STUDENT_DIRECT_Q_SELF_COT
dft_loss: false
only_alignment_loss: false
enable_gradient_checkpointing: true
enable_low_memory_forward: true
record_only_shift_layer_for_alignment: true
record_masked_hidden_states_only: true

recovery_vector_init:
  multimodal_extracted:
    path: ""
    source_model_name: ""
    source_dataset_name: ""
  unimodal_extracted:
    path: "/data1/wzy/cot-mimic/results/average_cot_vectors/internlm2_5-7b-chat_strategyqa_correct_only_500_avg_cot_vector_mimic_20260406.pt"
    source_model_name: "internlm2_5-7b-chat"
    source_dataset_name: "strategyqa"

validation_eval:
  enabled: false
  record_subdir: learnable
  query_split: test
  support_split: test
  max_eval_samples: 687
  batch_size: 1
  use_cot: false
  eval_mode: EVAL_WITH_COT_VECTOR_DIRECT_Q
  generation_args:
    num_beams: 1
    max_new_tokens: 64
    length_penalty: 0.0
    do_sample: false
    temperature: 0.0
    top_p: 1.0

data:
  name: strategyqa
  source: /data/share/strategy_qa/
  query_split: test
  support_split: test
  num_query_samples: 500
  num_shot: 0
  max_seq_len: 1536
  seed: 42
  num_workers: 4
  use_self_cot: true
  self_cot_path: "/data1/wzy/cot-mimic/results/self_cot/strategyqa/internlm2_5-7b-chat_strategyqa_self_cot_500_correct_only.json"
  training_mode: ${training-mode}
  train_use_images: false

only_shift_at_layer: 17
layer_train_mode: "single_layer"
model_layers: 32
start_layer: 0
end_layer: 32
shift_layers_combinations: [[17]]
