defaults:
  - exp_settings
  - _self_

runname: "mathvista-qwen2.5-vl-mimic-l9"
devices: 0
dtype: torch.float16
resume: False
lr: ${peft.lr}
weight_decay: 1e-3
warmup_step: 0.1
batch_size: 1
epochs: 6
ce_loss_weight: ${peft.ce_loss_weight}
align_loss_weight: ${peft.align_loss_weight}
strategy: auto
accumulate_grad_batches: 4
grad_clip_val: 1.0
precision: 16-mixed

model_name: qwen2.5-vl-7b-instruct
training-mode: TRAIN_STUDENT_DIRECT_Q_SELF_COT
dft_loss: False
only_alignment_loss: False

data:
  name: mathvista
  num_query_samples: 500
  num_shot: 0
  max_seq_len: 2048
  seed: 42
  num_workers: 4
  use_self_cot: True
  self_cot_path: "/data1/wzy/cot-mimic/output/mathvista/self_cot_data_correct_only.json"
  training_mode: ${training-mode}

only_shift_at_layer: 9
layer_train_mode: "single_layer"
model_layers: 28
start_layer: 0
end_layer: 28
shift_layers_combinations: [[9]]
