defaults:
  - _self_
#  - exp_settings

runname: "default"
devices: 0
dtype: torch.float16
resume: False
lr: ${peft.lr}
weight_decay: 1e-3
warmup_step: 0.1
batch_size: 2
epochs: null # int or null. if null, decide by train.py
ce_loss_weight: ${peft.ce_loss_weight}
align_loss_weight: ${peft.align_loss_weight}
# strategy: deepspeed_stage_2_offload  # Options: "deepspeed_stage_2_offload" / "ddp"
strategy: auto  # Options: "deepspeed_stage_2_offload" / "ddp"
accumulate_grad_batches: 2
grad_clip_val: 1.0
precision: 16-mixed  # 16-mixed; formally training need 32
method_name: trainable_multimodal_extracted_vector_recovery
benchmark_name: ${data.name}

init_mode: random
loss_mode: null
random_init_std: 1e-3

# New: Number of tokens from the end of the sequence to align for hidden states
align_num_tokens: 10

model_name: llama-3.1-8b-instruct # 确保模型名称正确
training-mode: TRAIN_STUDENT_DIRECT_Q # TRAIN_STUDENT_DIRECT_Q_SELF_COT; TRAIN_STUDENT_DIRECT_Q
dft_loss: False
only_alignment_loss: True

recovery_vector_init:
  multimodal_extracted:
    path: ""
    source_model_name: ""
    source_dataset_name: ""
  unimodal_extracted:
    path: ""
    source_model_name: ""
    source_dataset_name: ""

validation_eval:
  enabled: False
  record_subdir: learnable
  query_split: null
  support_split: null
  max_eval_samples: null
  batch_size: 1
  eval_mode: EVAL_WITH_COT_VECTOR_DIRECT_Q
  generation_args:
    num_beams: 1
    max_new_tokens: 4096
    length_penalty: 0.0
    do_sample: False
    temperature: 0.0
    top_p: 1.0

data:
  name: gsm8k
  num_query_samples: 3000 # 训练集样本数量，根据您的需求调整
  num_shot: 0 # 对于学生模型，0 表示直接提问，1 表示 1-shot 示例
  max_seq_len: 2048 # 最大序列长度，确保能容纳教师和学生模型输入
  seed: 3407
  num_workers: 5
  use_self_cot: False
  self_cot_path: "/data1/wzy/cot-mimic/output/gsm8k/self_cot_data_correct_only.json"

  # New: Training mode for GSM8KDataset
  # "TRAIN_STUDENT_ONESHOT": 学生模型使用1shot Q+最终结果示例进行训练
  # "TRAIN_STUDENT_DIRECT_Q": 学生模型直接给Q进行训练
  training_mode: ${training-mode} # 初始选择一种训练模式

encoder:
  cls: src.shift_encoder.AttnApproximator # 使用AttnApproximator作为CoT向量的实现
  attn_strategy: "VECTOR_SHIFT|LEARNABLE_SHIFT_SCALE" # MimIC中Attention的策略
  ffn_strategy: "VECTOR_SHIFT" # MimIC中FFN的策略
  shift_scale_init_value: 1.0 # 学习到的移位尺度的初始值

use_cot_vector_type: "mimic"
#static_shift_scale: 1.0
#use_static_mu: True # Set to True to use a static mu value for extracted CoT vectors
#static_mu_value: ${static_shift_scale}  # The static mu value to use when use_static_mu is True
only_shift_at_layer: -1

# Layer Evaluation Modes:
# 1. "single_layer": Iterate through layers from start_layer to end_layer.
# 2. "combinations": Iterate through pre-defined combinations in shift_layers_combinations.
# 3. "dense": all layers injected
layer_train_mode: "single_layer" # Default mode

# Parameters for single_layer evaluation mode:
model_layers: 32 # Total number of layers in your model, e.g., 28 for Qwen2.5-Math-7B-Instruct
start_layer: 0   # Inclusive starting layer index for the loop
end_layer: 32    # Exclusive ending layer index for the loop (e.g., 28 means layers 0-27)

# Parameters for combinations evaluation mode:
shift_layers_combinations: [[3,7]]
# Instruct: [[3, 13], [3,7,13],[3,7,13,24]]
# base:[[15],[7,15], [3,7,15],[3,7,15,23]]
